### ISSUE TITLE
Question about the decoding settings for alpaca_eval

### ISSUE THREAD

**Issue by huchinlp** [allenai/open-instruct#100]
Hi, according to the alpaca farm paper, they used sampling with a temperature setting of 0.7 for text generation. However, it appears your code utilizes greedy decoding (temperature=0), which could result in the generation of repetitive tokens and potential failure in the evaluation process (with alpaca_eval).

**Comment by hamishivi** [comment]
Hi, yeah, we decided to go for greedy decoding for our case and didn't tune generation parameters. Newer versions of alpaca eval should be able to handle this, and we are looking into updating alpaca eval accordingly!
