### ISSUE TITLE
微调报错

### ISSUE THREAD

**Issue by QingChengLineOne** [allenai/open-instruct#104]
(codellama) root@rt-res-public24-86f789d7bc-bqb49:/public/zzy/open-instruct# python open_instruct/reformat_datasets.py --dataset evol_codealpaca meta_math SlimOrca WizardLM_evol_instruct_V2_196k
usage: reformat_datasets.py [-h] [--raw_data_dir RAW_DATA_DIR] [--output_dir OUTPUT_DIR]
                            [--dataset {super_ni,cot,flan_v2,dolly,self_instruct,unnatural_instructions,stanford_alpaca,code_alpaca,gpt4_alpaca,sharegpt,baize,oasst1,lima,wizardlm,open_orca,hard_coded,science,tulu_v1,tulu_v2} [{super_ni,cot,flan_v2,dolly,self_instruct,unnatural_instructions,stanford_alpaca,code_alpaca,gpt4_alpaca,sharegpt,baize,oasst1,lima,wizardlm,open_orca,hard_coded,science,tulu_v1,tulu_v2} ...]]
                            [--seed SEED]
reformat_datasets.py: error: argument --dataset: invalid choice: 'evol_codealpaca' (choose from 'super_ni', 'cot', 'flan_v2', 'dolly', 'self_instruct', 'unnatural_instructions', 'stanford_alpaca', 'code_alpaca', 'gpt4_alpaca', 'sharegpt', 'baize', 'oasst1', 'lima', 'wizardlm', 'open_orca', 'hard_coded', 'science', 'tulu_v1', 'tulu_v2')
(codellama) root@rt-res-public24-86f789d7bc-bqb49:/public/zzy/open-instruct#

**Comment by hamishivi** [comment]
Hi, it looks like you are trying to format datsets not in the list of datasets supported in our codebase - happy to provide more advice if you provide more details!
