### ISSUE TITLE
flan-v2 data

### ISSUE THREAD

**Issue by constanzafierro** [allenai/open-instruct#106]
I can't access the data in https://beaker.org/api/v3/datasets/ could you clarify what data specifically you used for the [flan-v2](https://huggingface.co/allenai/open-instruct-flan-v2-7b) model you trained? I would like to have a look at the examples.

Thanks!

**Comment by hamishivi** [comment]
Hi - you can download our mixture from huggingface and look at examples where the dataset id is flan_v2, e.g.: https://huggingface.co/datasets/allenai/tulu-v2-sft-mixture/viewer/default/train?f[dataset][value]=%27flan_v2%27

I'll look into why the beaker datasets setup isn't working....

**Comment by hamishivi** [comment]
Sorry for the wait! We just merged a PR to download from huggingface instead. You can check the files [here](https://huggingface.co/datasets/hamishivi/tulu_mix_store).
