### ISSUE TITLE
QLoRA is very slow

### ISSUE THREAD

**Issue by SihengLi99** [allenai/open-instruct#109]
Hi,

I find that qlora is much slower than lora with the same lora config.
Could you please explain the reason for this?

Best

**Comment by SihengLi99** [comment]
I found that the time cost of QLoRa is five times that of LoRa.

**Comment by hamishivi** [comment]
Hi, that sounds odd - at the very least, QLoRa should take a similar time as LoRA with similar config. Did you raise the batch size with QLoRa (which should be doable thanks to the lower memory footprint)?

**Comment by SihengLi99** [comment]
Thanks for the quick reply!
I did not raise the batch size to guarantee a fair comparison.


Hamish Ivison ***@***.***> 于2024年2月8日周四 00:45写道：
