### ISSUE TITLE
LICENSE.txt not visible unless you agree to the LICENSE on Huggingface

### ISSUE THREAD

**Issue by ykoreeda02** [allenai/open-instruct#11]
Hi, thanks for the effort to make this model accessible!

I am cross-posting the discussion that I put on Huggingface, because I realized that people may not be following the discussion on Huggingface.

https://huggingface.co/allenai/tulu-65b/discussions/1

I wanted to obtain an access to this model, which requires me to agree to the terms and condtions:

> I agree to abide by the terms of the license associated to this artifact, including domain and used-based restrictions

And, it seems that the terms and conditions are written inside LICENSE.txt:

> This model is licensed under the AI model license given in LICENSE.txt along with the original Llama license (llama_license.txt).

The problem is that you cannot see LICENSE.txt unless you have obtained access to the model. It seems 232 people who downloaded the model already didn't care about this, but could you consider putting the LICENSE on the model card or have it accessible by other means?

**Comment by hamishivi** [comment]
Hi, yeah, good point. [I've added a PR](https://github.com/allenai/open-instruct/pull/13) to have the licenses in this repo, and once this is merged I'll update the gated model descriptions to point to this.

**Comment by hamishivi** [comment]
Closing since the PR is merged and I've made the edits to link to these from huggingface.
