### ISSUE TITLE
Insufficient permission to download, CoT data

### ISSUE THREAD

**Issue by dxlong2000** [allenai/open-instruct#115]
Hi, 

When I tried to download the data from BEAKER without my authentification, I got this error:

```
wget -P data/raw_train/cot/ https://beaker.org/api/v3/datasets/01GXZ52K2Q932H6KZY499A7FE8/files/cot_zsopt.jsonl
--2024-02-18 09:11:57--  https://beaker.org/api/v3/datasets/01GXZ52K2Q932H6KZY499A7FE8/files/cot_zsopt.jsonl
Resolving beaker.org (beaker.org)... 35.233.175.200
Connecting to beaker.org (beaker.org)|35.233.175.200|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

When I tried to create an account and download, I got insufficient permission to view.
```
{"code":403,"message":"01GXZ52K2Q932H6KZY499A7FE8: insufficient permission to view"}
```

Can you please advise and double check to make it publicly viewable?

**Comment by yizhongw** [comment]
Hi @dxlong2000 , the permission of our beaker workspace has been changed to non-public recently. We will seek other ways to host the original data.

Meanwhile, if you just want to access the Tulu2 data mixture, you can find they on huggingface. See this issue: https://github.com/allenai/open-instruct/issues/106

**Comment by pminervini** [comment]
Hi all, is there any news on this?

**Comment by hamishivi** [comment]
Sorry for the wait! We just merged a PR to download from huggingface instead. You can check the files [here](https://huggingface.co/datasets/hamishivi/tulu_mix_store).
