### ISSUE TITLE
[Potential bug] lambda function in evaluation scripts

### ISSUE THREAD

**Issue by ChenWu98** [allenai/open-instruct#117]
Hi! I tried to run the following cmd:
```bash
python -m eval.gsm.run_eval \
    --data_dir data/eval/gsm/ \
    --max_num_examples 5 \
    --save_dir results/gsm/tulu-2-7B-cot-8shot \
    --model allenai/tulu-2-7b \
    --tokenizer allenai/tulu-2-7b \
    --n_shot 8 \
    --use_chat_format \
    --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format
```
but it seems that the formatted prompts are the same for all samples. I think this is due to the use of lambda function [this line](https://github.com/allenai/open-instruct/blob/763206f5b8fe340c7833c438113f69ba7bca8886/eval/gsm/run_eval.py#L74) in the last merged PR: lambda function inside a loop does not capture a variable's current value but rather its reference. Not sure if I missed something, but if this is the case, let me know if I can help draft a PR to fix it!

**Comment by hamishivi** [comment]
Hi, yeah sorry about this! Should be fixed with #99!
