### ISSUE TITLE
`pip install requirements.txt` breaks now

### ISSUE THREAD

**Issue by dwadden** [allenai/open-instruct#136]
I just had to re-build my conda env for open-instruct, and found that when I ran `pip install -r requirements.txt` I got the following:

```
(open-instruct) $ pip install -r requirements.txt
Collecting git+https://github.com/yizhongw/transformers.git@left_padding (from -r requirements.txt (line 19))
...
ERROR: Could not find a version that satisfies the requirement torch<=2.0.1 (from versions: 2.2.0, 2.2.1)
ERROR: No matching distribution found for torch<=2.0.1
```

Do you know if it's safe to upgrade torch?

**Comment by hamishivi** [comment]
It might be safe to upgrade to 2.1. I think 2.2 doesn't work with vLLM yet? Feel free to test this out.

**Comment by natolambert** [comment]
I also got this recently. I installed torch manually and then it worked.
Though, bumping is probably good. I can test this.

**Comment by dwadden** [comment]
Thanks!
