### ISSUE TITLE
full dataset of flan v2

### ISSUE THREAD

**Issue by BaohaoLiao** [allenai/open-instruct#14]
Hi,

you offer a re-sampled version of flan v2 in prepare_train_data.py. May I ask how I find the full flan v2 dataset? I see there are multiple versions in huggingface and am not sure which version you use.

**Comment by BaohaoLiao** [comment]
It seems you use this version https://huggingface.co/datasets/SirNeural/flan_v2. Close this issue now

**Comment by constanzafierro** [comment]
I can't access the data in https://beaker.org/api/v3/datasets/ could you clarify what data specifically you used for the flan-v2 model you trained? I would like to have a look at the examples.

Thanks!
