### ISSUE TITLE
Get Stuck while using alpaca-farm

### ISSUE THREAD

**Issue by YSLIU627** [allenai/open-instruct#141]
Hi, we are using your evaluation module for alpaca-farm task. We successfully got all the inference results for our model for evaluation. But it got stuck during the GPT4-annotation process. The last trace is INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK" and there is no response anymore. I would appreciate it if you could offer help.

**Comment by hamishivi** [comment]
Hi, yeah I've seen this once or twice before, and it seems somewhat random. I would try just rerunning the eval. AlpacaEval caches annotations so it shouldn't cost too much extra. I'm making a PR for a newer version of AlpacaEval that hopefully fixes some of this! (#139)

**Comment by YSLIU627** [comment]
Thank you very much!
