### ISSUE TITLE
Running eval requires openai key

### ISSUE THREAD

**Issue by natolambert** [allenai/open-instruct#152]
Probably want to make this optional.
Can close this if beaker secret just wasn't being loaded correctly, but not what I was expecting.

**Comment by hamishivi** [comment]
Yeah, we should make this optional. For evals that don't require an openai key, you can set `OPENAI_API_KEY` to any value and it should be fine.

**Comment by hamishivi** [comment]
Fixed with #135 - now a warning is simply logged. In the future, it probably would be good to add asserts to any tests that require openai keys so they error earlier rather than later.
