### ISSUE TITLE
Migrate to tokenizer + fastchat conv templates

### ISSUE THREAD

**Issue by natolambert** [allenai/open-instruct#155]
Realistically, doing our own is a losing battle, let's migrate to something maintained.

**Comment by hamishivi** [comment]
There is a start at this here: https://github.com/allenai/open-instruct/blob/main/eval/templates.py#L112
But more formal integrations with fastchat would be good. I think supporting more flexible generation in general is good. E.g. llama 3 with its multiple eos tokens.

**Comment by yizhongw** [comment]
I came aross this issue when I want to use a different chat template to train models. So, I made this [PR](https://github.com/allenai/open-instruct/pull/350). It should support user-defined chat templates.

**Comment by hamishivi** [comment]
Closing since #350 kinda resolves this.
