### ISSUE TITLE
Is the split_all function in split_sharegpt_conversations.py very slow?

### ISSUE THREAD

**Issue by AnnyShen55** [allenai/open-instruct#208]
Hi, is that natural for the split_all function to take a long time to run (especially the content[begin:end] part)? Thank you!

**Comment by AnnyShen55** [comment]
Basically stuck at this function for 20 hours...looks like both the cpu and gpu are idle...Any ideas?

**Comment by AnnyShen55** [comment]
does torch==2.3.0 has to be from the source not from pip install torch==2.3.0?

**Comment by AnnyShen55** [comment]
Reinstalled pytorch from source, still stuck at this place.

**Comment by hamishivi** [comment]
Hi, the split function should not be slow. It takes < 1min to run on our machines. I would say try adjusting the number of workers to better match your machine might help: https://github.com/allenai/open-instruct/blob/main/scripts/split_sharegpt_conversations.py#L66

However, I cannot reproduce this issue locally - using the dockerfile provided with our repo, I am able to run the script without issue, and the splitting takes 1-2minutes max for the 2k and 4k lengths.

**Comment by AnnyShen55** [comment]
OMG, yea, it's the number of workers! I reduced it and it goes! Thank you so much!
