### ISSUE TITLE
More details about individual task score and dataset stats?

### ISSUE THREAD

**Issue by macabdul9** [allenai/open-instruct#21]
Hi, 

Great work. 

I was wondering if you can provide individual task scores (particularly for MMLU and BBH tasks) as well as stats about dataset mixing (if you have). eg: how many instruction-response pairs mixing resulted in for both human-mix and Tulu mix?

Thanks and congrats again on great work. 

cc: @yizhongw @hamishivi

**Comment by yizhongw** [comment]
Hi @macabdul9 thanks for being interested in the work!

> if you can provide individual task scores (particularly for MMLU and BBH tasks)?

Yeah we have those numbers in our log, but it's a bit time-consuming to collect them for all models. Are there some models that you are particularly interested in?

> how many instruction-response pairs mixing resulted in for both human-mix and Tulu mix?

You can look up the number of instances for each dataset in the Table 1 of our paper, and add them up for the mixes.

**Comment by macabdul9** [comment]
Thanks @yizhongw . 

Can you share vanilla 7 and 13b and human-mix and tulu 7b and 13b results for individual tasks in MMLU and BBH. Thaks again.

**Comment by hamishivi** [comment]
Hi - Sorry for the long delay in this, this issue got lost in a shuffle. Here is a link with a zip containing results for Tulu 1 and the human mixes that I could find internally. Some come from reruns of the models and evals so not guarantees these match exactly the paper results:
[results.zip](https://github.com/allenai/open-instruct/files/14173434/results.zip)

I couldn't find our vanilla 7b breakdowns, unfortunately. Sorry! 
Hope this helps!
