### ISSUE TITLE
Any strategies for writing function convert_(dataset_name)_data for a custom dataset on hugging face?

### ISSUE THREAD

**Issue by AnnyShen55** [allenai/open-instruct#210]
Hello, would you mind telling me some strategy suggestions for writing the convert_(dataset_name)_data functions in reform_datasets.py on a dataset from huggingface? Thank you so much!

**Comment by natolambert** [comment]
Hey @AnnyShen55 -- we're moving a bit away from that script, but it looks like these functions.
https://github.com/allenai/open-instruct/blob/42c1fa3c10d0f39112e40146c0cebfcce88346f2/open_instruct/utils.py#L59

Then you can call
```
data_formatted = dataset.map(format_fnc)
```

**Comment by AnnyShen55** [comment]
Got it, any more insights that you may kindly give? Thank you!

**Comment by natolambert** [comment]
Make copies of datasets in your preferred format :)
