### ISSUE TITLE
Error when run ./scripts/finetune_with_accelerate.sh

### ISSUE THREAD

**Issue by AnnyShen55** [allenai/open-instruct#211]
Hi, I got the following error when run ./scripts/finetune_with_accelerate.sh:
[rank0]: Traceback (most recent call last):
[rank0]:   File "=/open-instruct/open_instruct/finetune.py", line 693, in <module>
[rank0]:     main()
[rank0]:   File "/open-instruct/open_instruct/finetune.py", line 551, in main
[rank0]:     accelerator.init_trackers(
[rank0]:   File "/home/user1/anaconda3/envs/llmft2/lib/python3.10/site-packages/accelerate/accelerator.py", line 685, in _inner
[rank0]:     return PartialState().on_main_process(function)(*args, **kwargs)
[rank0]:   File "/home/user1/anaconda3/envs/llmft2/lib/python3.10/site-packages/accelerate/accelerator.py", line 2586, in init_trackers
[rank0]:     tracker.store_init_configuration(config)
[rank0]:   File "/home/user1/anaconda3/envs/llmft2/lib/python3.10/site-packages/accelerate/tracking.py", line 79, in execute_on_main_process
[rank0]:     return PartialState().on_main_process(function)(self, *args, **kwargs)
[rank0]:   File "/home/user1/anaconda3/envs/llmft2/lib/python3.10/site-packages/accelerate/tracking.py", line 211, in store_init_configuration
[rank0]:     self.writer.add_hparams(values, metric_dict={})
[rank0]:   File "/home/user1/anaconda3/envs/llmft2/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 341, in add_hparams
[rank0]:     exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
[rank0]:   File "/home/user1/anaconda3/envs/llmft2/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 316, in hparams
[rank0]:     raise ValueError(
[rank0]: ValueError: value should be one of int, float, str, bool, or torch.Tensor

Any suggestions? Thank you!

**Comment by AnnyShen55** [comment]
Got the same issue for the lora finetuning.

**Comment by AnnyShen55** [comment]
I use hf-internal-testing/llama-tokenizer as the tokenizer input and hpcai-tech/Colossal-LLaMA-2-7b-base as the model input, and others in the sh file are unchanged.

**Comment by AnnyShen55** [comment]
Also tried mistralai/Mistral-7B-v0.1 as model and tokenizer but still got the same issue.

**Comment by AnnyShen55** [comment]
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

MODEL_SIZE=7B
NUM_GPUS=8
BATCH_SIZE_PER_GPU=1
TOTAL_BATCH_SIZE=128
GRADIENT_ACC_STEPS=$(($TOTAL_BATCH_SIZE/$NUM_GPUS/$BATCH_SIZE_PER_GPU))
echo "Training llama model ${MODEL_SIZE} using $NUM_GPUS GPUs, $BATCH_SIZE_PER_GPU batch size per GPU, $GRADIENT_ACC_STEPS gradient accumulation steps"

# You can also set --gradient_checkpointing or use `stage3_offloading_accelerate.conf` to save memory, 
# but it will trade off speed.
accelerate launch \
    --mixed_precision bf16 \
    --num_machines 1 \
    --num_processes $NUM_GPUS \
    --use_deepspeed \
    --deepspeed_config_file configs/ds_configs/stage3_no_offloading_accelerate.conf \
    open_instruct/finetune.py \
    --model_name_or_path mistralai/Mistral-7B-v0.1 \
    --tokenizer_name mistralai/Mistral-7B-v0.1 \
    --use_slow_tokenizer \
    --train_file data/processed/tulu_v2/tulu_v2_data.jsonl \
    --max_seq_length 8192 \
    --preprocessing_num_workers 128 \
    --per_device_train_batch_size $BATCH_SIZE_PER_GPU \
    --gradient_accumulation_steps $GRADIENT_ACC_STEPS \
    --learning_rate 2e-5 \
    --lr_scheduler_type linear \
    --warmup_ratio 0.03 \
    --weight_decay 0. \
    --num_train_epochs 2 \
    --output_dir output/tulu_v2_${MODEL_SIZE}/ \
    --with_tracking \
    --report_to tensorboard \
    --logging_steps 1               This is what i currently have for finetune_with_accelerate.sh.

**Comment by natolambert** [comment]
@AnnyShen55 what is your python / accelerate version? Try passing
```
--report_to wandb
```
Not sure what's going on in tensorboard.

**Comment by AnnyShen55** [comment]
Cool, it works now!
