### ISSUE TITLE
Precompute DPO logprobs

### ISSUE THREAD

**Issue by natolambert** [allenai/open-instruct#213]
To save compute.
Another hard issue :)

**Comment by natolambert** [comment]
A sketch of how this could work.

Add an option in `dpo_tune` where instead of using concatenated_forward, we run just forward for each with an optional save of the logprobs.

https://github.com/allenai/open-instruct/blob/42c1fa3c10d0f39112e40146c0cebfcce88346f2/open_instruct/dpo_tune.py#L568

**Comment by hamishivi** [comment]
Closed by #395
