### ISSUE TITLE
max_seq_length and per_device_train_batch_size

### ISSUE THREAD

**Issue by tangzhy** [allenai/open-instruct#25]
Hi, 

I wonder what `max_seq_length` and `per_device_train_batch_size` for `huggyllama/llama-7b` you are using in all experiments?

I'm trying to use `max_seq_length=2048` and `per_device_batch_size=2` on 4xA100 80GB gpus with deepspeed as you provided in `[finetune_with_accelerate.sh](https://github.com/allenai/open-instruct/blob/main/scripts/finetune_with_accelerate.sh)`.

I constantly meet CUDA OOM error.

Seeking your help.

**Comment by yizhongw** [comment]
The script provided  in [finetune_with_accelerate.sh](https://github.com/allenai/open-instruct/blob/main/scripts/finetune_with_accelerate.sh) is what we used for training the 7B model. Did you also set `--use_flash_attn`?
