### ISSUE TITLE
missing sharegpt_html_cleaned_and_split_2048.json

### ISSUE THREAD

**Issue by ppalantir** [allenai/open-instruct#272]
Thanks for your awesome work!

I met the same issue during the training data preparation

> Processing datasets...
> Processing super_ni data with default configurations...
> Processing cot data with default configurations...
> Processing flan_v2 data with default configurations...
> Processing dolly data with default configurations...
> Processing self_instruct data with default configurations...
> Processing unnatural_instructions data with default configurations...
> Processing stanford_alpaca data with default configurations...
> Processing code_alpaca data with default configurations...
> Processing gpt4_alpaca data with default configurations...
> Processing sharegpt data with default configurations...
> Traceback (most recent call last):
> FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_train/sharegpt/sharegpt_html_cleaned_and_split_2048.json
> 

And I checked the downloading process of ShareGPT:

> Downloading ShareGPT dataset...
> Saving to: ‘data/raw_train/sharegpt/sg_90k_part1_html_cleaned.json’
> Saving to: ‘data/raw_train/sharegpt/sg_90k_part2_html_cleaned.json’
> Splitting the ShareGPT dataset with 2048 max tokens per conversation...
> python: can't open file './open-instruct/scripts/split_sharegpt_conversations.py': [Errno 2] No such file or directory
> Splitting the ShareGPT dataset with 4096 max tokens per conversation...
> python: can't open file './open-instruct/scripts/split_sharegpt_conversations.py': [Errno 2] No such file or directory

Does the missing `split_sharegpt_conversations.py` lead to missing sharegpt_html_cleaned_and_split_2048?
where could I get the `split_sharegpt_conversations.py` ?
Thanks

**Comment by hamishivi** [comment]
Hi, this should be fixed when I merge #275 - we just forgot to change a path when moving some scripts around.
