### ISSUE TITLE
Error with batch inference

### ISSUE THREAD

**Issue by raojay7** [allenai/open-instruct#29]
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [25,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Error when generating completions for batch:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

The above error occurs when testing bbh and seems to be due to batch inference.

**Comment by kelvennn** [comment]
I met the same problem, and it seems caused by the trained model. I train it with LoRA, and the error happended. 

The evaluation of BBH and GSM can be work well when I loaded other trained LoRA model instead such as (https://huggingface.co/samwit/alpaca7B-lora/) or just loaded LLama model.

**Comment by hamishivi** [comment]
Hi, could you provide more details, such as the command you are running?

Sometimes this happens if you are loading a tokenizer without added padding tokens, as the code tries to access an embedding index that doesn't exist.

**Comment by hamishivi** [comment]
Closing since stale.
