### ISSUE TITLE
multinode training

### ISSUE THREAD

**Issue by clu2gt** [allenai/open-instruct#327]
Hello! thank you for your contribution!
I want to ask if this code supports multi-machine training?

**Comment by notoookay** [comment]
Hi, maybe you could try it yourself. Check [this](https://github.com/allenai/open-instruct#:~:text=We%20have%20not%20tested%20multi%2Dnode%20training%20with%20this%20script%2C%20but%20it%20should%20work.).

**Comment by hamishivi** [comment]
Hi, we currently do support multi-node training via deepspeed and accelerate, for example see configs/beaker_configs/default_finetune_multinode.yaml - specifically, the argument given. You'll probably need to adjust it a little for your own environment (i.e., working out how to get the right ip for main_process_ip).
The [official accelerate docs](https://huggingface.co/docs/transformers/main/en/deepspeed#multi-node-deployment) may also be useful to look at!
