### ISSUE TITLE
What kind of rewarding mechanism does tulu-v2.5-13b-uf-rm use?

### ISSUE THREAD

**Issue by arunasank** [allenai/open-instruct#359]
What's the best way to tell which reward function was used to train a model in the Tulu-v2.5 suite? I am particularly interested in https://huggingface.co/allenai/tulu-v2.5-13b-uf-rm

**Comment by hamishivi** [comment]
If you look at the table for some of the PPO-trained models in the Tulu 2.5 suite we show the base, reward, value, and final trained model in the same row: hhttps://huggingface.co/allenai/tulu-v2.5-ppo-13b-uf-mean-70b-uf-rm#model-family

Hope that helps!
