### ISSUE TITLE
"Eval Script Naming Issue: 'trutufulqa.sh' should be 'truthfulqa.sh'"

### ISSUE THREAD

**Issue by pendulum445** [allenai/open-instruct#394]
I noticed that one of the files `scripts/eval/trutufulqa.sh` is named `trutufulqa`, but it should actually be `truthfulqa` (LOL, small typo!). 😂This might cause some confusion when referencing the file.  Additionally, the script paths are also using `trutufulqa` instead of `truthfulqa`. Could you kindly update both the file name and the script paths to `truthfulqa` for consistency? Thanks a bunch! 🙌
![QQ_1729679180034](https://github.com/user-attachments/assets/ef3da667-93d7-4309-ad01-cef472df26a6)

**Comment by natolambert** [comment]
@pendulum445 can you open a PR to fix it :)?

**Comment by pendulum445** [comment]
@natolambert I have opened a Pull Request to address the issue. You can find it [here](https://github.com/allenai/open-instruct/pull/400). Thanks. 😊
