### ISSUE TITLE
Mismatch MMLU results with arxiv paper

### ISSUE THREAD

**Issue by constanzafierro** [allenai/open-instruct#43]
I ran the MMLU eval with the `flan-v2-7b` and `stanford-alpaca-7b` and I've got different results than those reported in the paper. Does the arxiv version has the latest numbers? I run the eval script with the flags `--ntrain 0 --eval_batch_size 2 --load_in_8bit --use_chat_format`

```
$ cat outputs/mmlu/stanford-alpaca-7b-0shot/metrics.json
{"average_acc": 0.4154678820680815, "subcat_acc": {"math": 0.27725563909774437, "health": 0.44146341463414634, "physics": 0.3546875, "business": 0.5720823798627003, "biology": 0.45594713656387664, "chemistry": 0.3333333333333333, "computer science": 0.36650485436893204, "economics": 0.3719676549865229, "engineering": 0.35172413793103446, "philosophy": 0.3812127236580517, "other": 0.46266094420600856, "history": 0.4989247311827957, "geography": 0.5151515151515151, "politics": 0.5200617283950617, "psychology": 0.4675885911840968, "culture": 0.5843373493975904, "law": 0.3448667044809983}, "cat_acc": {"STEM": 0.341948310139165, "humanities": 0.39086078639744953, "social sciences": 0.4712382190445239, "other (business, health, misc.)": 0.4666872301048735}}
```

```
$ cat outputs/mmlu/flan-v2-7b-0shot/metrics.json
{"average_acc": 0.4544936618715283, "subcat_acc": {"math": 0.2932330827067669, "health": 0.4634146341463415, "physics": 0.340625, "business": 0.5926773455377574, "biology": 0.4801762114537445, "chemistry": 0.35313531353135313, "computer science": 0.39563106796116504, "economics": 0.4029649595687331, "engineering": 0.36551724137931035, "philosophy": 0.397117296222664, "other": 0.5570815450643777, "history": 0.6053763440860215, "geography": 0.5050505050505051, "politics": 0.5509259259259259, "psychology": 0.5522904062229905, "culture": 0.6114457831325302, "law": 0.38740782756664777}, "cat_acc": {"STEM": 0.3548707753479125, "humanities": 0.434643995749203, "social sciences": 0.5193370165745856, "other (business, health, misc.)": 0.5144972239358421}}
```

**Comment by yizhongw** [comment]
Hi @constanzafierro are you using our latest codebase? I recently had some bug fix (PR [1](https://github.com/allenai/open-instruct/pull/38) and PR [2](https://github.com/allenai/open-instruct/pull/39). These can lead to slight slight change in the numbers. I compared the numbers you reported here with the ones in our paper. It seems the difference is very subtle?

**Comment by constanzafierro** [comment]
Hey, 
Thanks for the answer! I ran it including those fixes. The difference is not huge but significant, in the paper the FLAN MMLU result is 50.7 whereas I got 0.45, and for Alpaca the paper reported 45.1 and I obtained 0.41

**Comment by hamishivi** [comment]
Hi, in the paper we report 41.5 0-shot MMLU  for Alpaca, and 45.4 0-shot MMLU for Flan (see Table 7 in our paper on arxiv).

This seems to match your results exactly!

**Comment by constanzafierro** [comment]
You're right I was looking at the 13B numbers, thanks for looking into this anyways! :)
