### ISSUE TITLE
File does not exists

### ISSUE THREAD

**Issue by YathishPoojary98** [allenai/open-instruct#450]
There is no file named scripts/tokenize_dataset.py to tokenize the data in IndicInstruct repository.

**Comment by hamishivi** [comment]
Hi, this is the open-instruct repository - I would suggest raising an issue in the IndicInstruct repo if you have an issue with that repository. Feel free to re-open with more details if you have questions about open-instruct!

**Comment by YathishPoojary98** [comment]
There is no option for raising an issue in the IndicInstruct repo.
