### ISSUE TITLE
Docker build faild caused by copy oe-eval-internal  file not exist

### ISSUE THREAD

**Issue by wgimperial** [allenai/open-instruct#462]
Sorry for bothering you for this problem. I met the following problem, when I try to build docker image from Dockerfile:
 ---> 54a36d612093
Step 31/41 : COPY open_instruct open_instruct
 ---> 6a712db7b437
Step 32/41 : COPY oe-eval-internal oe-eval-internal
COPY failed: file not found in build context or excluded by .dockerignore: stat oe-eval-internal: file does not exist

**Comment by vwxyzjn** [comment]
Hi, feel free to comment it out. Oe-eval-internal is not a requirement for running open-instruct

**Comment by wgimperial** [comment]
it‘s ok, thanks
