### ISSUE TITLE
effective batch size

### ISSUE THREAD

**Issue by DachengLi1** [allenai/open-instruct#464]
<img width="989" alt="Screenshot 2024-11-29 at 1 28 34 PM" src="https://github.com/user-attachments/assets/a04365e8-4212-48ca-9f83-1e14a184f4bf">

Hello team, thanks a lot for the great work! If I understand correctly, for 8 GPUs, I should set NUM_PROCESSES=8, PER_DEVICE_BATCH_SIZE=1, GRADIENT_ACCUMULATIONS=16 for an effective batch size of 128?

Thank you very much for any help!

**Comment by vwxyzjn** [comment]
Oh hey @DachengLi1, nice to meet you yesterday! Yes, you should use 16 gradient accumulation steps. Thanks for the catch!

I have updated the documentation accordingly:

<img width="877" alt="image" src="https://github.com/user-attachments/assets/210c43eb-ef58-4be9-a509-42adf2b2c386">
