### ISSUE TITLE
how to train with own data? 

### ISSUE THREAD

**Issue by yxchng** [allenai/open-instruct#466]
is there a doc on how to prepare (format required) and train with own data?

**Comment by vwxyzjn** [comment]
Pleas check out the https://github.com/allenai/open-instruct/blob/main/docs/tulu3.md and the corresponding dataset. E.g., `allenai/tulu-3-sft-mixture` is https://huggingface.co/datasets/allenai/tulu-3-sft-mixture. You can create a dataset with the same format.
