### ISSUE TITLE
How to fine-tune Phi-3-small-128k-instruct for RLVR?

### ISSUE THREAD

**Issue by yxchng** [allenai/open-instruct#470]
Training command:

> 
> /home/user/reasoning/open-instruct/open_instruct/ppo_vllm_thread_ray_gtrl.py \
> --dataset_mixer "{\"ai2-adapt-dev/gsm8k_math_ifeval_ground_truth_mixed\": 1.0}" \
> --dataset_train_splits train \
> --dataset_eval_mixer "{\"ai2-adapt-dev/gsm8k_math_ground_truth\": 1.0}" \
> --dataset_eval_splits test \
> --max_token_length 2048 \
> --max_prompt_token_length 2048 \
> --response_length 2048 \
> --model_name_or_path microsoft/Phi-3-small-128k-instruct \
> --reward_model_path allenai/Llama-3.1-Tulu-3-8B-RM \
> --non_stop_penalty \
> --stop_token eos \
> --temperature 1.0 \
> --ground_truths_key ground_truth \
> --chat_template tulu \
> --sft_messages_key messages \
> --learning_rate 3e-7 \
> --total_episodes 10000000 \
> --penalty_reward_value -10.0 \
> --deepspeed_stage 3 \
> --per_device_train_batch_size 4 \
> --local_rollout_forward_batch_size 4 \
> --local_mini_batch_size 64 \
> --local_rollout_batch_size 64 \
> --actor_num_gpus_per_node 3 \
> --vllm_tensor_parallel_size 1 \
> --beta 0.05 \
> --apply_verifiable_reward true \
> --output_dir output/rlvr_phi7b \
> --seed 3 \
> --num_evals 3 \
> --save_freq 100 \
> --reward_model_multiplier 0.0 \
> --gradient_checkpointing \
> --with_tracking

Currently getting this error:

```
Traceback (most recent call last):
  File "/home/user/reasoning/open-instruct/open_instruct/ppo_vllm_thread_ray_gtrl.py", line 1808, in <module>
    main(*parser.parse())
  File "/home/user/reasoning/open-instruct/open_instruct/ppo_vllm_thread_ray_gtrl.py", line 1606, in main
    tokenizer.add_special_tokens({"pad_token": "[PAD]"})  # NOTE: we do not resize the embedding
  File "/home/user/cache/conda/envs/openinstruct/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 986, in add_special_tokens
    added_tokens = self.add_tokens(added_tokens, special_tokens=True)
  File "/home/user/cache/conda/envs/openinstruct/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1036, in add_tokens
    return self._add_tokens(new_tokens, special_tokens=special_tokens)
  File "/home/user/cache/huggingface/modules/transformers_modules/microsoft/Phi-3-small-128k-instruct/ad85cab62be398dc90203c4377a4ccbf090fbb36/tokenization_phi3_small.py", line 220, in _add_tokens
    raise ValueError(
ValueError: For now, we do not support unknown special tokens
In the future, if there is a need for this, we can add special tokens to the tokenizer
starting from rank 100261 - 100263 and then 100266 - 100275.
And finally, we can re-construct the enc object back
```

I only change model_name_or_path. How should I resolve this? 

Is reward_model_path needed? Since it is using verifiable reward, I presume it is not used?

**Comment by vwxyzjn** [comment]
`--reward_model_path allenai/Llama-3.1-Tulu-3-8B-RM` cause the issue: you cannot use this RM with phi-3. Please train your own RM following https://github.com/allenai/open-instruct/blob/main/docs/tulu3.md#llama-31-tulu-3-8b-rm-reproduction. 

You can also just say `--reward_model_path microsoft/Phi-3-small-128k-instruct` to initialize the RM from the instruct model, which should also work for RLVR (albeit having lower average scores than initializing from the RM; see our paper).

**Comment by yxchng** [comment]
@vwxyzjn why reward model is still needed when it is doing verifiable reward which should not be using reward model? what am i misunderstanding here?

**Comment by yxchng** [comment]
i tried changing to phi for the reward model but also meeting this error 

```
raise ValueError(
ValueError: For now, we do not support unknown special tokens
In the future, if there is a need for this, we can add special tokens to the tokenizer
starting from rank 100261 - 100263 and then 100266 - 100275.
And finally, we can re-construct the enc object back
```
