### ISSUE TITLE
[Question] About the training time of RLVR

### ISSUE THREAD

**Issue by chchch0109** [allenai/open-instruct#485]
Hi, thanks for the great work!
Can you provide the estimated runtime of RLVR on a single dataset(like GSM8k) under your GPU settings(2 nodes in paper)?

**Comment by natolambert** [comment]
Hey @chchch0109 -- we're adding more of these numbers to the next version of the paper. Lemme copy them here.
Interesting there was another question #484 :). 

> The 8B reward model is trains in 9 hours on 8 H100 gpus, while the full 8B RL run takes ~65 hours on 8 GPUs and the full 70B RL run takes ~60 hours on 48 GPUs.
Note, for both of these models we took an earlier than final checkpoint from the run.
