### ISSUE TITLE
Request for Code of Synthesizing for Target Skills

### ISSUE THREAD

**Issue by DeepLSUN** [allenai/open-instruct#486]
Hello,  
I was reading your paper and found that in section 3.1.2 "Synthesizing for Target Skills," you mentioned using a persona-driven methodology to generate prompts targeting specific skills. I would like to ask if you have released the code for this part, as I couldn't find it in the repository. Additionally, I would like to know if the code under `open_instruct/rejection_sampling` in the repository is used for data generation.
Thank you for your assistance!

**Comment by fabrahman** [comment]
Hi @DeepLSUN thank you or your interest.

We will release the persona-driven data generation pipeline this week. Stay tuned!

While we have used `open_instruct/rejection_sampling` for some experiments, we didn't use this for our final data generation pipeline.

**Comment by DeepLSUN** [comment]
Thank you very much for your reply, and I look forward to your upcoming updates.

**Comment by fabrahman** [comment]
@DeepLSUN Persona-driven data gen is available [here](https://github.com/allenai/open-instruct/tree/main/scripts/persona_driven_data_gen)
