### ISSUE TITLE
Any plan to support mt-bench evaluation?

### ISSUE THREAD

**Issue by HuihuiChyan** [allenai/open-instruct#50]
I think [https://github.com/lm-sys/FastChat/tree/main/fastchat/llm_judge](mt-bench) is also a good evaluation set. Do you have any plan to support mt-bench evaluation in the future?

**Comment by yizhongw** [comment]
Hi @HuihuiChyan thanks for the suggestion! Yeah we are aware of mt-bench as a good evaluation for multi-turn chatbot. But adding this benchmark is not on our priority list rn. If you are interested, you are very welcome to create a pr for adding this!
