### ISSUE TITLE
Does LoRa finetuning give weight diff or actual weight?

### ISSUE THREAD

**Issue by macabdul9** [allenai/open-instruct#51]
Do we need to recover weights after LoRa fine-tuning or do we get the final weights?

Also, can you provide some information about which weights are recovered and which are difference? It's not clear from "`Some of the checkpoints are released as weight diffs to the base model (mostly for LLaMa 1).`" in the doc here: https://github.com/allenai/open-instruct#weight-diff-script 

Maybe you can add a column here: https://github.com/allenai/open-instruct#released-checkpoints specifying which checkpoints are diff and which ones are recovered weights. Thanks. 

cc: @yizhongw @hamishivi @eltociear

**Comment by hamishivi** [comment]
Hi,

We don't currently officially support LoRa finetuning (there is some code in repo for this, we will more properly update it and add documentation soon). The current lora script merges the lora modules back into the model after training, but you could just comment out that line if you wanted.

All released LLaMa weights are weight diffs, and non-llama models are not weight diffs. We fully-finetuned these models, so they are full weight diffs, not lora modules. I'll clarify that in the readme in the next update, thanks for the comment!

**Comment by hamishivi** [comment]
Hi,

I just added QLoRA and LoRA support officially. When you finetune with (Q)LoRA, you will result in saving the LoRA modules, which you can then merge with a base model using the `merge_lora.py` script. Check out `scripts/finetune_lora_with_accelerate.sh` and `scripts/finetune_qlora_with_accelerate.sh` for examples on how to use.

And just to clarify, all our released checkpoints so far are fully-finetuned weight diffs, with the exception of the Pythia and OPT models - no LoRA modules are involved.

Thanks!
