### ISSUE TITLE
Estimated timeline for human data release

### ISSUE THREAD

**Issue by martiansideofthemoon** [allenai/open-instruct#53]
Hi @yizhongw,
Thank you very much for this excellent release!

I was wondering what was the estimated timeline for the release of the human evaluation data and interface (the README mentioned it's coming soon)? It would be very helpful for my research!

Thank you,
Kalpesh

**Comment by yizhongw** [comment]
Hi @martiansideofthemoon yeah, thanks for the reminder lol. We will spare some time to release them next week (the code needs some cleaning). Will ping back here once done.

**Comment by martiansideofthemoon** [comment]
Hi @yizhongw, wanted to follow up again here and see if there has been any release update? Thank you!

**Comment by hamishivi** [comment]
Hi, this was released semi-recently: https://github.com/allenai/open-instruct/tree/main/human_eval
