### ISSUE TITLE
It seems that the tokens <|user|> and <|assistant|> are not treated as special tokens.

### ISSUE THREAD

**Issue by Zcchill** [allenai/open-instruct#54]
It seems that the tokens <|user|> and <|assistant|> are not treated as special tokens.(i.e. these 2 tokens will be tokenized into many tokens). Is that right? Or it is a mistake?

**Comment by yizhongw** [comment]
Hi @Zcchill thanks for raising the question. This is expected - we just tokenize them as normal text. You can add them as special tokens after initializing the tokenizer, but the embeddings of the new tokens will be initialized to be something not that meaningful (could be random or an average of some existing embeddings) and might hurt the performance.
