### ISSUE TITLE
CUDA OOM for qlora

### ISSUE THREAD

**Issue by tangzhy** [allenai/open-instruct#65]
Hi, i'm trying your qlora script(https://github.com/allenai/open-instruct/blob/main/scripts/finetune_qlora_with_accelerate.sh) for a node of eight A100 80GB gpus.

But I get the error
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB (GPU 7; 79.20 GiB total capacity; 75.10 GiB already allocated; 279.56 MiB free; 77.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Any suggestions?

**Comment by tangzhy** [comment]
Maybe you turned on `use_8bit_optimizer` in your experiments?

**Comment by hamishivi** [comment]
Hi, I didn't use the 8bit optimizer. I'm able to run the example script fine on 2 80GB A100s... 

 If you're using a large model (>=30B), you'll need to turn on gradient checkpointing, and might need to reduce the lora rank.

**Comment by tangzhy** [comment]
@hamishivi Thanks for your reply. That works! Have you conducted exp for llama-70b? How do you set up rank and alpha and learning rate? Looking forward to your suggestions!

**Comment by hamishivi** [comment]
Hi, we have very recently experimented with the 70b size. For that, we used:
- lora rank: 64
- lora alpha: 16
- learning rate: 1e-4
- context length: 4096
- number of epochs: 5 
- GPUs: 4 nodes, 32 GPUs (A100 80GB)

You'll need to turn on gradient checkpointing.

We found this gave fairly reasonable results, but we're still in the process of benchmarking and testing.

**Comment by hiteshis** [comment]
hey @hamishivi, can you please share in detail what worked for 70B. I am trying following on 8 nodes with 4 GPUs (32 GPUs total) for SFT but still running into OOM:
      --num_machines 8 
      --num_processes 32 
      --use_deepspeed
      --deepspeed_config_file ds_configs/stage3_offloading_accelerate.conf 
      --mixed_precision bf16  
      --use_flash_attn
      --use_lora
      --lora_rank 64
      --lora_alpha 16
      --lora_dropout 0.05
      --use_slow_tokenizer 
      --max_seq_length 2048 
      --preprocessing_num_workers 16 
      --gradient_checkpointing
      --per_device_train_batch_size 1
      --gradient_accumulation_steps 2
      --learning_rate 5.5e-6 
      --lr_scheduler_type cosine 
      --warmup_ratio 0.1 
      --weight_decay 0. 
      --num_train_epochs 2

**Comment by hamishivi** [comment]
Hi, this all looks very reasonable to me. I'll note that our run used A100 80GB GPUs, so if you have less memory on your GPUs this will limit what you can do. One important thing to note is that the Qlora training requires data-parallel (it's actually hardcoded in the train script), so you need to be able to fit the qlora model on one gpu. This is because (last I checked) QLoRA does not work with FSDP/Deepspeed. It looks like it is slowly getting worked on in bitsandbytes (see e.g. https://github.com/TimDettmers/bitsandbytes/pull/970), but I don't think it's quite there yet - feel free to try and make it work and submit a PR if you do!

So I would check that you can run qlora 70b on one gpu at first. If not - you won't be able to do data parallel training. Your main hope would be to swap to regular lora or even full-finetuning, which I think should work with distributed training (but of course will use much more memory overall).

**Comment by hiteshis** [comment]
Thank you for following up! yes, I am using A100 80GB GPUs. 
You are right, with deepspeed 3 i run into ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

**Comment by hiteshis** [comment]
The way I am launching this multinode job as:  

     accelerate launch 
      --num_machines 8 --num_processes 32 --main_process_ip $${MASTER_ADDR} --main_process_port $${MASTER_PORT} --machine_rank $${NODE_RANK}
      --use_deepspeed
      --deepspeed_config_file ds_configs/stage3_offloading_accelerate.conf 
      --mixed_precision bf16
      SFT.py

No other processes in GPU. Quick question: do you --use_qlora and what are the preprocessing_num_workers for you?

**Comment by hamishivi** [comment]
Oh yeah, you are completely right - you need to have the `use_qlora` flag set to actually use QLoRA. Without this, you are definitely going to hit OOM issues. My bad, I missed that in the list of commands you showed me. Here is the precise command we used for training on one node:

```bash
accelerate launch --num_machines 1 --num_processes 8 open_instruct/finetune.py \
--model_name_or_path <model path> \
--tokenizer_name <model path> \
--use_slow_tokenizer \
--train_file <train_data> \
--use_flash_attn \
--gradient_checkpointing \
--use_lora \
--use_qlora \
--lora_rank 64 \
--lora_alpha 16 \
--lora_dropout 0.1 \
--max_seq_length 4096 \
--preprocessing_num_workers 64 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 16 \
--learning_rate 1e-4 \
--lr_scheduler_type linear \
--warmup_ratio 0.03 \
--weight_decay 0. \
--num_train_epochs 5 \
--output_dir output/ \
--with_tracking --report_to wandb --checkpointing_steps epoch \
--logging_steps 1
```

The `preprocessing_num_workers` is just for data preprocessing, it shouldn't affect CUDA oom. If your training dataset is large, you can get distributed training timeouts if the preprocessing takes over 30 minutes. You can configure this with the `timeout` flag if this is too short.

**Comment by hiteshis** [comment]
No worries! I do set the use_qlora and throws me
ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

Do you also have the launch command handy for 70b model on 8 nodes?

**Comment by hamishivi** [comment]
Here's the command we used for 4 nodes. We have some in-house compute management platform stuff that handles the rank/ip stuff for us - this is what provides e.g. `BEAKER_REPLICA_RANK`.

```bash
unset CUDA_LAUNCH_BLOCKING && accelerate launch \
  --mixed_precision bf16 \
--num_machines 4 \
--num_processes 32 \
--machine_rank $BEAKER_REPLICA_RANK \
--main_process_ip $BEAKER_LEADER_REPLICA_HOSTNAME \
--main_process_port 29400 \
open_instruct/finetune.py \
--model_name_or_path <model_path> \
--tokenizer_name <model_path> \
--use_slow_tokenizer \
--train_file <data_path> \
--use_flash_attn \
--gradient_checkpointing \
--use_lora \
--use_qlora \
--lora_rank 64 --lora_alpha 16 --lora_dropout 0.1 \
--max_seq_length 4096 \
--preprocessing_num_workers 64 \
--per_device_train_batch_size 1 --gradient_accumulation_steps 4 \
--learning_rate 1e-4 --lr_scheduler_type linear --warmup_ratio 0.03 \
--weight_decay 0. --num_train_epochs 5 --output_dir /output/ \
--with_tracking --report_to wandb --checkpointing_steps epoch --logging_steps 1
```
