### ISSUE TITLE
This script does not work with cerebras gpt and gpt neox.

### ISSUE THREAD

**Issue by kevinscaria** [allenai/open-instruct#71]
I am using finetune_with_accelerate.sh for finetuning. It works for pythia models but does not work with cerebras gpt and gpt neox.  Is there something I need to change with the tokenizers?

**Comment by hamishivi** [comment]
Probably - the GPT-Neox code in there was only tested for pythia models, so you might have to adjust it if the tokenizers are different. Check out https://github.com/allenai/open-instruct/blob/main/open_instruct/finetune.py#L459.

If you share a specific error, I might be able to help!
