### ISSUE TITLE
Rotary position embedding scaling 8k for Llama2? 

### ISSUE THREAD

**Issue by shi-kejian** [allenai/open-instruct#77]
Thank you again for this great effort. 

Does anyone managed to do rotary position embedding scaling to 8k for Llama2, and tuned those using open-instruct? 
Discussions are much appreciated.

**Comment by hamishivi** [comment]
Hi! We didn't experiment with the rotary scaling stuff, although we have some new models trained with 8k context length (using llama2) out of the box coming out soon!
I'll leave the issue open in case anyone else has tried it out and wants to comment :)
