### ISSUE TITLE
RecursionError when running weight diff script

### ISSUE THREAD

**Issue by rahuln** [allenai/open-instruct#8]
I'm trying to use the weight diff script provided in the repo to rebuild one of the fine-tuned checkpoints, and I'm running into some issues. I started by setting up a new Conda environment (Python version 3.11.3), installed the requirements from `weight-diff-requirements.txt` using `pip`, downloaded the 7B-parameter LLaMA checkpoint as well as the `allenai/open-instruct-sni-7B` model diff from Huggingface, and then ran the `weight_diff.py` script as specified in `README.md`. This causes the following error:

```
  File "/gscratch/ark/rahuln/miniconda3/envs/weight-diff/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1155, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gscratch/ark/rahuln/miniconda3/envs/weight-diff/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 250, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gscratch/ark/rahuln/miniconda3/envs/weight-diff/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 257, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
           ^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

Is this a known issue with `weight_diff.py`? Any suggestions on how to go about fixing it? Thanks!

**Comment by rahuln** [comment]
I discovered a possible fix for this: changing `AutoTokenizer` to `LlamaTokenizer` in `weight_diff.py` seems to resolve the issue, but I'm not sure if this ends up loading the tokenizer incorrectly – let me know if this is the right solution!

**Comment by arazd** [comment]
> I discovered a possible fix for this: changing `AutoTokenizer` to `LlamaTokenizer` in `weight_diff.py` seems to resolve the issue, but I'm not sure if this ends up loading the tokenizer incorrectly – let me know if this is the right solution!

Thumbs up, since this solved the issue for me too!
