### ISSUE TITLE
balanced_low_0 Related Issue During Inference

### ISSUE THREAD

**Issue by mshen2** [allenai/open-instruct#89]
Hi, I noticed in `scripts/eval/bbh.sh`, if two or more CUDA devices are available, for example, `CUDA_VISIBLE_DEVICES=0,1`, it will give "Expected all tensors to be on the same device, but found at least two devices" error. If using `auto` instead of `balanced_low_0` for device_map, then it is fine. I am wondering probably I am missing something? Thanks!

**Comment by hamishivi** [comment]
Hi - are you still having this issue? I recommend using vllm if you can, since it is much faster.
