### ISSUE TITLE
Support for tuning on chat data

### ISSUE THREAD

**Issue by xufangzhi** [allenai/open-instruct#93]
Hello，
thanks for sharing the code base.

Can the open-instruct code base support for tuning on conversational data (e.g., ShareGPT) ?

**Comment by hamishivi** [comment]
Hi, yes, we support training on multi-turn chat data and in fact used shareGPT for training tulu! You can have multiple turns in the conversation by just having multiple entries in the 'messages' field in the data (see the [uploaded tulu v2](https://huggingface.co/datasets/allenai/tulu-v2-sft-mixture) mix for an example).
