### ISSUE TITLE
File Not Found error while running finetune_lora_with_accelerate.sh

### ISSUE THREAD

**Issue by palash04** [allenai/open-instruct#94]
Following file seems to be missing in the entire repo **oasst1_data.jsonl**
Where can I find this file?

**Comment by hamishivi** [comment]
Hi, if you run `scripts/prepare_train_data.sh` it should download and prepare the training data and download and create that file. Generally, our training scripts are intended as examples of how to use this repo - feel free to replace that file with a file containing your own training data in the required format (jsonl with fields like our [uploaded Tulu mix](https://huggingface.co/datasets/allenai/tulu-v2-sft-mixture)).
