### ISSUE TITLE
Embedding resizing logic may be flawed

### ISSUE THREAD

**Issue by prajdabre** [allenai/open-instruct#95]
In the file finetune.py, lines 467-471 talk about resizing the embedding matrix of LLAMA when adding the padding token.

https://github.com/allenai/open-instruct/blob/60ceefa6d9339663843decb69a1e6546fc717c4f/open_instruct/finetune.py#L467

Issue: The size of the vocab inferred via the embedding matrix is 0, presumably due to safetensors. This means, resizing will always happen if I use a variant of LLAMA2 which I have modified myself which may already contain the pad token. 

However, when a model which is available in its safetensors format, does model.resize_token_embeddings(len(tokenizer)) even work?

This is likely a huggingface issue but I thought I would raise it here.

TIA.

**Comment by hamishivi** [comment]
Hi, thanks for pointing this out! This is in fact indeed an issue with deepspeed init I think. I recently merged a fix for this, so the parameters are gathered before resizing, which hopefully solves your issue here. Feel free to re-open the issue if you are still having problems!
