### ISSUE TITLE
[Issue with solution] Merging qlora error: open_instruct/merge_lora.py:25 TypeError: 'QuantState' object does not support item assignment

### ISSUE THREAD

**Issue by ZucksLiu** [allenai/open-instruct#97]
bitsandbytes==0.41.3post2

After training qlora model and trying to merge it with the base model with merge_lora.py, I found the following issue: 

                quant_state[2] = dtype

This will result in the error 'TypeError: 'QuantState' object does not support item assignment'.

It is because QuantState does not support item assignment, see its implementation at:  
https://github.com/TimDettmers/bitsandbytes/blob/947db7cf783466cd90dc3c05178107d744f949ae/bitsandbytes/functional.py#L589C9-L590C1

A possible corerction could be change it to 
                quant_state.dtype = dtype

**Comment by hamishivi** [comment]
Hi - thanks for pointing this out, looks like a change in the updated bitsandbytes! The suggested fix seems to work, I've merged it in.
